---
title: "testing"
author: "Kevin Guan"
date: '2022-05-09'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warnings = FALSE, message = FALSE)

library(tidyverse)

up1 = read.csv("All_Up.csv", header = FALSE, sep = ",")
up_list1 <- split(up1, seq(nrow(up1)))
up_list1 <- unname(unlist(up_list1))

up2 = read.csv("All_up.txt", header = FALSE, sep = ",")
up_list2 <- split(up2, seq(nrow(up2)))
up_list2 <- unname(unlist(up_list2))

up3 = read.csv("All_Up_Alen.txt", header = FALSE, sep = ",")
up_list3 <- split(up3, seq(nrow(up3)))
up_list3 <- unname(unlist(up_list3))

left1 = read.csv("All_left.csv", header = FALSE, sep = ",")
left_list1 <- split(left1, seq(nrow(left1)))
left_list1 <- unname(unlist(left_list1))

left2 = read.csv("All_left.txt", header = FALSE, sep = ",")
left_list2 <- split(left2, seq(nrow(left2)))
left_list2 <- unname(unlist(left_list2))

left3 = read.csv("All_Left_Alen.txt", header = FALSE, sep = ",")
left_list3 <- split(left3, seq(nrow(left3)))
left_list3 <- unname(unlist(left_list3))

down1 = read.csv("All_down.csv", header = FALSE, sep = ",")
down_list1 <- split(down1, seq(nrow(down1)))
down_list1 <- unname(unlist(down_list1))

down2 = read.csv("All_down.txt", header = FALSE, sep = ",")
down_list2 <- split(down2, seq(nrow(down2)))
down_list2 <- unname(unlist(down_list2))

down3 = read.csv("All_down_Alen.txt", header = FALSE, sep = ",")
down_list3 <- split(down3, seq(nrow(down3)))
down_list3 <- unname(unlist(down_list3))
```

```{r classifier}
Classifer <- function(wave_file, 
                      window_size_test = 2000, 
                      window_size_return = 15000,
                      increment = 100, 
                      threshold = 80) {
  
  wave_seq = wave_file
  testStat_zero = 0
  testStat_amp = 0
  Linterval = c()
  Uinterval = c()
  Zeros = c()
  Amplitude = c()
  lower_interval = 1
  max_time = length(wave_seq)
  
  #streaming Code
  while(max_time > lower_interval + window_size_test)
  {
    upper_interval = lower_interval + window_size_test
    interval = wave_seq[lower_interval:upper_interval]

    testStat_zero <- sum(interval[1:(length(interval) - 1)] *
                     interval[2:(length(interval))] <= 0) 
    
    testStat_amp <- max(interval) - min(interval)
    
    # Linterval = append(Linterval,lower_interval)
    # Uinterval = append(Uinterval,upper_interval)
    Zeros = append(Zeros,testStat_zero)
    Amplitude = append(Amplitude,testStat_amp)
    
    if (testStat_zero <= 40 & testStat_amp >= 15 ) {
      upper_return = lower_interval + window_size_return
      Linterval = append(Linterval,lower_interval)
      Uinterval = append(Uinterval,upper_return)
      lower_interval = lower_interval+ window_size_return
    }
    else {
      lower_interval = lower_interval + increment
    }
    
 #   lower_interval = lower_interval + increment

    #Detecting events
    # prediction = append(prediction, statSignal)  
    # 
    # if (testStat < 200) {
    #   testStat2 = 2
    #   count = count + 1
    # }  else {
    #   testStat2 = 1
    # }
    
 
       
  #   if (testStat2 == 2) {
  #     if (testStat_Amplitude > 90) {
  #       maxval = which.max(interval)
  #       minval = which.min(interval)
  #       prediction = append(prediction, 
  #                                 ifelse(maxval < minval,  
  #                                        "L", "R"))
  #       
  #       Linterval = append(Linterval,lower_interval) #recording value of lower interval
  #       Uinterval = append(Uinterval,upper_interval) #recording value of upper interval
  #       lower_interval = upper_interval + window_size*0.5
  #     } 
  #     else if (testStat_Amplitude < 90 & testStat_Amplitude >30) {
  #         prediction = append(prediction, "up/down")
  #         Linterval = append(Linterval,lower_interval)
  #         Uinterval = append(Uinterval,upper_interval)
  #         lower_interval = upper_interval + window_size*0.5
  #     } 
  #   else {
  #       lower_interval = lower_interval + increment
  #     }
  # }
  
  # Return dataframe of predictions and their intervals 
  }
  return(data.frame(Lower_interval = Linterval,
                    Upper_interval = Uinterval
                    # Zero = Zeros,
                    # Amp = Amplitude
                   ))
}
```

```{r}
test = up_list3-median(up_list3)
Classifer(test)
```


```{r}
test = down_list3-median(down_list3)
down_intervals = Classifer(test)

ggplot() +
  geom_line(aes(y = test, x = c(1:length(test)))) +
  geom_rect(aes(xmin=down_intervals$Lower_interval, 
                xmax=down_intervals$Upper_interval, ymin=-Inf, 
                ymax=Inf), 
            fill = "green", alpha = 0.2)

pt(3.25, 8, lower.tail = F)
```


```{r}
ggplot() +
  geom_line(aes(y = test, x = seq(1:length(test))))
```

